-- MySQL Script generated by MySQL Workbench
-- Tue Mar 28 15:25:29 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product` (
  `barcode` INT NOT NULL,
  `group` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `weight` FLOAT NOT NULL,
  `price` FLOAT NOT NULL,
  `type` TINYINT NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`barcode`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`store` (
  `idStore` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idStore`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`countProducts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`countProducts` (
  `idStore` INT NOT NULL,
  `idProduct` INT NOT NULL,
  `count` INT NOT NULL DEFAULT 0,
  INDEX `sid_idx` (`idStore` ASC) VISIBLE,
  INDEX `pid_idx` (`idProduct` ASC) VISIBLE,
  CONSTRAINT `csid`
    FOREIGN KEY (`idStore`)
    REFERENCES `mydb`.`store` (`idStore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cpid`
    FOREIGN KEY (`idProduct`)
    REFERENCES `mydb`.`product` (`barcode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customer` (
  `idcustomer` INT NOT NULL AUTO_INCREMENT,
  `nameCustomer` VARCHAR(45) NULL,
  `cardNumber` INT NULL,
  PRIMARY KEY (`idcustomer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sale` (
  `idSale` INT NOT NULL AUTO_INCREMENT,
  `idStore` INT NOT NULL,
  `idCustomer` INT NOT NULL,
  `idProduct` INT NOT NULL,
  `date` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`idSale`),
  INDEX `sid_idx` (`idStore` ASC) VISIBLE,
  INDEX `cid_idx` (`idCustomer` ASC) VISIBLE,
  INDEX `pid_idx` (`idProduct` ASC) VISIBLE,
  CONSTRAINT `sid`
    FOREIGN KEY (`idStore`)
    REFERENCES `mydb`.`store` (`idStore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cid`
    FOREIGN KEY (`idCustomer`)
    REFERENCES `mydb`.`customer` (`idcustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pid`
    FOREIGN KEY (`idProduct`)
    REFERENCES `mydb`.`product` (`barcode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
